//--Summary:
//  Create a program that utilizes goroutines to run the provided calculation
//  function on a number of jobs. The results from the goroutines must be
//  communicated back to the main thread using a channel, and then added
//  together.
//
//--Requirements:
//* Run `longCalculation` for each job generated by the `makeJobs` function
//* Each job must be run in a separate goroutine
//* The result from `longCalculation` must be provided to the main function
//  using a channel
//* Sum the results from each job to generate a final result, and print it
//  to the terminal

package main

import (
	"fmt"
	"math/rand"
	"time"
)

type Job int

func longCalculation(i Job) int {
	duration := time.Duration(rand.Intn(1000)) * time.Millisecond
	time.Sleep(duration)
	fmt.Printf("Job %d complete in %v\n", i, duration)
	return int(i) * 30
}

func makeJobs() []Job {
	jobs := make([]Job, 0, 100)
	for i := 0; i < 100; i++ {
		jobs = append(jobs, Job(rand.Intn(10000)))
	}
	return jobs
}

func runCalculation(results chan int, i Job) {
	//* The result from `longCalculation` must be provided to the main function
	//  using a channel
	results <- longCalculation(i)
}

func main() {
	//rand.Seed(time.Now().UnixNano())
	jobs := makeJobs()
	results := make(chan int)

	//* Run `longCalculation` for each job generated by the `makeJobs` function
	for i := 0; i < len(jobs); i++ {
		//* Each job must be run in a separate goroutine
		go runCalculation(results, jobs[i])
	}

	resultsCalculated := 0
	sum := 0

	for {
		result := <-results
		resultsCalculated++
		//* Sum the results from each job to generate a final result, and print it
		//  to the terminal
		sum += result
		if resultsCalculated == len(jobs) {
			break
		}
	}
	fmt.Println("Sum is", sum)
	fmt.Println("Results calculated", resultsCalculated)
}
